---
# tasks file for mysqlinstall
#------------------------------------------------s6
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Installing Mysql
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set root user password
      mysql_user:
        name: root
        password: "{{root_password}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        login_user: root
        login_password: "{{root_password}}"
        state: present
        check_implicit_admin: yes
    
    - name: Remote anonymous users
      mysql_user:
        name: ''
        login_user: root
        login_password: "{{root_password}}"
        state: absent

    - name: Create admin user with remote access
      mysql_user:
        name: "{{admin_user}}"
        password: "{{admin_password}}"
        priv: '*.*:ALL'
        host: '*'
        append_privs: yes
        login_user: root
        login_password: "{{root_password}}"
        state: present

    - name: creating database
      mysql_db:
        name: "{{db_name}}"
        state: present
        login_user: root
        login_password: "{{root_password}}"

    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regex: '^bind-address\s*=\s*127.0.0.1'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
#------------------------------------------------
